version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - code-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - code-network

  elasticsearch:
    image: elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - "transport.host=localhost"
      - "bootstrap.system_call"
    volumes:
      - ./storage/data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - code-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=laravel.local
    volumes:
      - ./src:/var/www/html
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log
    depends_on:
      - php
      - mysql
    networks:
      - code-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    working_dir: /var/www/html
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./etc/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./storage/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - code-network

  postgres:
    image: postgres:11.1-alpine
    container_name: postgres
    working_dir: /var/www/html
    volumes:
      - ./storage/data/postgres:/var/lib/postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: laravel
    ports:
      - 5432:5432
    networks:
      - code-network

  php:
    build:
      context: ./etc/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./etc/php/php.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      - ./redis/redis-worker.conf /etc/supervisor/conf.d/
      - ./src:/var/www/html
      - ./log:/var/log
    ports:
      - 9000:9000
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
